wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5
hidden_size:
  value: 256
learning_rate:
  value: 1.0007540962740882
num_epochs:
  value: 50
patience:
  value: 10
scheduler_gamma:
  value: 0.5
scheduler_step_size:
  value: 5
weight_decay:
  value: 0
