wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.7
hidden_size:
  value: 128
learning_rate:
  value: 1.000069700754833
num_epochs:
  value: 50
patience:
  value: 10
scheduler_gamma:
  value: 0.5
scheduler_step_size:
  value: 10
weight_decay:
  value: 1.0e-05
