wandb_version: 1

batch_size:
  value: 16
dropout:
  value: 0.7
hidden_size:
  value: 256
learning_rate:
  value: 1.000216206400042
num_epochs:
  value: 50
patience:
  value: 10
scheduler_gamma:
  value: 0.1
scheduler_step_size:
  value: 10
weight_decay:
  value: 0
