services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-namenode
    expose:
      - "9870"
    ports:
      - "9870:9870"
    environment:
      - CLUSTER_NAME=hadoop
      - HDFS_USER=ravikumar
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:8020
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - airflow

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode
    hostname: hdfs-datanode  # Set a resolvable hostname
    expose:
      - "9864"
    ports:
      - "9864:9864"
    environment:
      - CLUSTER_NAME=hadoop
      - SERVICE_PRECONDITION=hdfs-namenode:9870
      - HDFS_USER=ravikumar
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:8020
      - HDFS_CONF_dfs_namenode_http_address=hdfs-namenode:9870
      - HDFS_CONF_dfs_datanode_hostname=hdfs-datanode  # Set Datanode hostname
    volumes:
      - datanode:/hadoop/dfs/data
    networks:
      - airflow
  
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_WEBUI_PORT=8081
      - HADOOP_USER_NAME=ravikumar
      - SPARK_SHUFFLE_SERVICE_ENABLED=false
    ports:
      - "8081:8081"
      - "7077:7077"
    volumes:
      - spark-data:/bitnami
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    networks:
      - airflow

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=7G
      - SPARK_WORKER_CORES=10
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - HADOOP_USER_NAME=ravikumar
      - SPARK_SHUFFLE_SERVICE_ENABLED=false
    volumes:
      - spark-data:/bitnami
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    depends_on:
      - spark-master
    networks:
      - airflow

volumes:
  namenode:
  datanode:
  spark-data:

networks:
  airflow:
    driver: bridge