services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-namenode
    expose:
      - "9870"
    ports:
      - "9870:9870"
    environment:
      - CLUSTER_NAME=hadoop
      - HDFS_USER=ravikumar
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:8020
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - hadoop_network
      - astronomer_a3954d_airflow

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode
    hostname: hdfs-datanode  # Set a resolvable hostname
    expose:
      - "9864"
    ports:
      - "9864:9864"
    environment:
      - CLUSTER_NAME=hadoop
      - SERVICE_PRECONDITION=hdfs-namenode:9870
      - HDFS_USER=ravikumar
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:8020
      - HDFS_CONF_dfs_namenode_http_address=hdfs-namenode:9870
      - HDFS_CONF_dfs_datanode_hostname=hdfs-datanode  # Set Datanode hostname
    volumes:
      - datanode:/hadoop/dfs/data
    networks:
      - hadoop_network
      - astronomer_a3954d_airflow
  
  spark:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker
    expose:
      - "8081"
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_PORT=8881
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_LOG=/spark/logs
      - SPARK_MASTER_WEBUI_PORT=8080
    volumes:
      - spark:/spark/logs
    depends_on:
      - spark-master
    networks:
      - hadoop_network

volumes:
  namenode:
  datanode:
  spark:

networks:
  hadoop_network:
    driver: bridge
  astronomer_a3954d_airflow:
    external: true