wandb_version: 1

batch_size:
  value: 16
dropout:
  value: 0.7
hidden_size:
  value: 256
learning_rate:
  value: 0.0001
num_epochs:
  value: 50
patience:
  value: 5
scheduler_gamma:
  value: 0.5
scheduler_step_size:
  value: 10
weight_decay:
  value: 0.0001
