wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.7
hidden_size:
  value: 128
learning_rate:
  value: 0.001
num_epochs:
  value: 50
patience:
  value: 5
scheduler_gamma:
  value: 0.5
scheduler_step_size:
  value: 5
weight_decay:
  value: 1.0e-05
