wandb_version: 1

batch_size:
  value: 16
dropout:
  value: 0.7
hidden_size:
  value: 128
learning_rate:
  value: 0.00013409175023542912
num_epochs:
  value: 50
patience:
  value: 10
scheduler_gamma:
  value: 0.5
scheduler_step_size:
  value: 5
weight_decay:
  value: 0
