wandb_version: 1

batch_size:
  value: 16
dropout:
  value: 0.5
hidden_size:
  value: 64
learning_rate:
  value: 0.00046490227933847314
num_epochs:
  value: 50
patience:
  value: 5
scheduler_gamma:
  value: 0.1
scheduler_step_size:
  value: 10
weight_decay:
  value: 1.0e-05
