wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.3
hidden_size:
  value: 256
learning_rate:
  value: 1.0008894283837682
num_epochs:
  value: 50
patience:
  value: 5
scheduler_gamma:
  value: 0.1
scheduler_step_size:
  value: 5
weight_decay:
  value: 1.0e-05
