method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  learning_rate:
    distribution: uniform
    min: 0.00001
    max: 0.001
  batch_size:
    values: [8, 16, 32, 64]
  hidden_size:
    values: [64, 128, 256]
  num_layers:
    values: [1, 2, 3]
  dropout:
    distribution: uniform
    min: 0.3
    max: 0.7
  weight_decay:
    distribution: uniform
    min: 1e-6
    max: 1e-4